version: '3'

services:
  stream_hsl:
    # image: ghcr.io/codions/docker-stream-server/docker-stream-server:latest
    # image: alqutami/rtmp-hls
    build: 
      context: ./docker-hls-stream
    container_name: stream_hsl
    restart: always
    volumes:
#       - ./docker-hls-stream/static:/hls/
      - /SISTEMAS/docker-hls-stream/static:/hls/
    environment:
      TZ: America/Cuiaba
    networks:
      - stream
    ports:
      - 1935:1935
      # - 47151:80
  api:
    container_name: api_stream
    networks:
      - stream
    build: ./api
    restart: always
    volumes: 
#       - ./docker-hls-stream/static:/home/stream
      - /SISTEMAS/docker-hls-stream:/home/stream
    environment:
      TZ: America/Cuiaba
    # ports:
    #   - 5000:5000
  
  proxy:
    image: nginx:1.20-alpine
    restart: always
    networks:
      - stream
    container_name: proxy
    volumes:
#       - ./proxy/stream.conf:/etc/nginx/conf.d/default.conf
      - "/SISTEMAS/certs:/certs"
      - /SISTEMAS/proxy/stream.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 443:443
    environment:
      TZ: America/Cuiaba

  certbot:
    image: certbot/certbot
    restart: on-failure
    command: certonly --webroot -w /app -d transmitir.biz -m comercial@vipcomsistemas.com.br --reinstall --expand   --renew-by-default   --reuse-key   --agree-tos
    volumes:
      - /SISTEMAS/docker-hls-stream/static:/app
      - "/SISTEMAS/certs/:/etc/letsencrypt" 
      - "/SISTEMAS/certs/:/var/lib/letsencrypt" 


networks:
  stream:
