version: '3'

services:
  stream_hsl:
    # image: ghcr.io/codions/docker-stream-server/docker-stream-server:latest
    image: alqutami/rtmp-hls
    container_name: stream_hsl
    ports:
      - 1935:1935 
      - 8080:8080 
